# Generated by Django 2.1.3 on 2018-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePeriod',
            fields=[
                ('periodID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sessionID', models.CharField(max_length=16)),
                ('duration', models.CharField(max_length=255)),
                ('repetitions', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='WearingSession',
            fields=[
                ('sessionID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('patientID', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
