# Generated by Django 2.1.3 on 2018-11-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePeriodSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Exercise Period Summary',
                'verbose_name_plural': 'Exercise Periods Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('database.exerciseperiod',),
        ),
        migrations.AlterField(
            model_name='exerciseperiod',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exerciseperiod',
            name='repetitions',
            field=models.IntegerField(),
        ),
    ]
