function [features] = extract_Features(segments)
% features = [pitch_features, roll_features];
% http://sclab.yonsei.ac.kr/courses/10TPR/10TPR.files/Gesture%20Recognition%20with%20a%203-D%20Accelerometer.pdf
features = [];

for i = 1:length(segments)
    % Pitch Statistical Features
    pitch_features_statistical = [...
        mean(segments(i).pitch), ...
        std(segments(i).pitch), ...
        skewness(segments(i).pitch), ... % symmetry
        kurtosis(segments(i).pitch), ... % measure of heavy or light tail; high kurtosis = heavy tail = outliers
        max(segments(i).pitch), ...
        min(segments(i).pitch), ...
        max(segments(i).pitch) - min(segments(i).pitch), ...
        segments(i).t(end) - segments(i).t(1), ...
        prctile(segments(i).pitch, 25), ...
        prctile(segments(i).pitch, 50), ...
        prctile(segments(i).pitch, 75)...
     ];
    
    % Pitch Frequency Features
    L = length(segments(i).pitch);
    Y = abs(fft(segments(i).pitch)/L);
    Y = Y(1:round(L/2+1));
    pitch_features_frequency = [...
        mean(Y), ...
        sum(Y.^2), ... % energy of spectrum
        entropy(Y) ];
    
    % Roll Statistical Features
    roll_features_statistical = [...
        mean(segments(i).roll), ...
        std(segments(i).roll), ...
        skewness(segments(i).roll), ... % symmetry
        kurtosis(segments(i).roll), ... % measure of heavy or light tail; high kurtosis = heavy tail = outliers
        max(segments(i).roll), ...
        min(segments(i).roll), ...
        max(segments(i).roll) - min(segments(i).roll), ...
        segments(i).t(end) - segments(i).t(1), ...
        prctile(segments(i).roll, 25), ...
        prctile(segments(i).roll, 50), ...
        prctile(segments(i).roll, 75)...
        ];
    
    % Roll Frequency Features
    L = length(segments(i).roll);
    Y = abs(fft(segments(i).roll)/L);
    Y = Y(1:round(L/2+1));
    roll_features_frequency = [...
        mean(Y), ...
        sum(Y.^2), ... % energy of spectrum
        entropy(Y) ];
    
    % Concatenate all features
    features = [features; pitch_features_statistical, pitch_features_frequency, roll_features_statistical, roll_features_frequency];
end
end