# Generated by Django 2.1.3 on 2018-11-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181122_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExercisePeriodSummary',
        ),
        migrations.AlterField(
            model_name='exerciseperiod',
            name='sessionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.WearingSession'),
        ),
    ]
