# Generated by Django 2.1.3 on 2019-03-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190228_1945'),
    ]

    operations = [
        
    ]
