# Generated by Django 2.1.3 on 2019-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_exerciseperiod_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseperiod',
            name='patientID',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
